# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

$script = <<SCRIPT
ssh-keygen -t rsa -P '' -f ~/.ssh/id_rsa
cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys
chmod 700 /root/.ssh/authorized_keys
apt-get -y install wget
wget http://severalnines.com/downloads/cmon/install-cc
chmod +x install-cc
S9S_CMON_PASSWORD=cmon S9S_ROOT_PASSWORD=root123 S9S_DB_PORT=3306 HOST=10.10.10.10 ./install-cc
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  4.times do |n|
    config.vm.define "vm"+(1+n).to_s do |cc|
        config.ssh.insert_key = false
        #cc.ssh.private_key_path = "<my private ssh key>"
        # change the box name if you want to use another box
        cc.vm.box = "ubuntu/trusty64"
        cc.vm.host_name = "n" + (1+n).to_s
        cc.vm.network :private_network, ip: "10.10.10.1" + n.to_s
        cc.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "768"]
        end
        if cc.vm.hostname == "n1" then
            cc.vm.network :forwarded_port, guest: 80, host: (8080+n)
            cc.vm.provision "shell", inline: $script, privileged: true
        end
    end
  end
end
